### ISSUE TITLE
a custom java security manager should be used

### ISSUE THREAD

**Issue by dvic** [tommite/bb-tools#1]
Without it, evil code could do harm to the system the app is running on. 

In particular, the FilePermission should be restricted, for more info: http://java.sun.com/developer/onlineTraining/Programming/JDCBook/appA.html

**Comment by tommite** [comment]
ya makes sense, go ahead pls :)

**Comment by dvic** [comment]
is there a way to run the bb-tools without the zip? If not, can you send me an example zip so I can work myself through the code.

**Comment by tommite** [comment]
Yep, check http://smaa.fi/tommi/courses/prog3/mysubmission.zip - just put it in another zip (it's without unit tests though).
